#!/usr/bin/env ruby
require 'digest/md5'
require 'yaml'

conf_file = ARGV.empty? ? "#{File.dirname(__FILE__)}/config.yml" : ARGV.shift
raise Error 'config.yml not found' unless File.exists? conf_file

app = "face.app"
id = Digest::MD5.hexdigest "#{Time.now.to_i}_#{`whoami`.strip}"
app_res_dir = "./#{app}/Contents/Resources"

puts "generate your app"
system "rm -rf #{app}" if File.exists? app
system "cp -R #{File.dirname(__FILE__)}/client/#{app} ./"
system "sips -s format icns icon.png -z 128 128 --out appIcon.icns"
File.rename('appIcon.icns', "#{app_res_dir}/appIcon.icns")
open("#{app_res_dir}/config.yml", 'w+') do |f|
  conf = YAML::load open(conf_file).read
  conf['id'] = id
  f.puts conf.to_yaml
end

puts "success!!"
