#!/usr/bin/env ruby
require 'digest/md5'

app = "shokai.app"
token = Digest::MD5.hexdigest "#{Time.now.to_i}_#{`whoami`}"

system "cp -R #{File.dirname(__FILE__)}/client/#{app} ./"
["#{app}/Contents/Resources/token.rb",
"server/helpers/token.rb"].each do |fname|
  open(fname, 'w+'){|f|
    f.write "def face_token\n  '#{token}'\nend"
  }
end
