#!/usr/bin/env ruby

Dir.glob(File.dirname(__FILE__)+'/gems/*').each do |gem|
  $:.unshift gem+'/lib'
end

require 'yaml'
require 'httpclient'
require 'digest/md5'
require 'uri'
require 'net/http'

begin
  @@conf = YAML::load open(File.dirname(__FILE__)+'/config.yml').read
rescue => e
  STDERR.puts e
  exit 1
end

c = HTTPClient.new
ARGV.each do |name|
  next unless File.exists? name
  begin
    hash = Digest::MD5.hexdigest open(name).read
    uri = URI.parse @@conf['api']+'/md5'
    check = Net::HTTP.start(uri.host, uri.port).
      post(uri.path, {:from => @@conf['id'], :md5 => hash}.map{|k,v|"#{k}=#{URI.encode v}"}.join('&'))
    if check.code.to_i == 200
      puts 'already uploaded'
      res = check.body
    elsif check.code.to_i == 404
      puts 'upload'
      res = c.post_content(@@conf['api']+'/file', {:file => open(name), :from => @@conf['id']})
    end
    if res =~ /^https?:\/\/.+/
      puts res
      system "echo #{res} | pbcopy"
      system "open #{res}"
    end
  rescue NoMethodError, StandardError => e
    STDERR.puts e
  rescue => e
    STDERR.puts e.res.body
    system "osascript -e 'tell application \"shokai\" to display dialog \"uplaod error - #{e.res.body}\"'"
  end
  sleep 1
end
